InputAsp/Models/Applicant.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InputAsp.Models
{
    public class Applicant
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [StringLength(150)]
        public string Name { get; set; }

        [Required]
        [StringLength(10)]
        public string Gender { get; set; }

        [Required]
        [Range(25,55, ErrorMessage = "Kamu esempe")]
        [DisplayName("Age in Years")]
        public int Age { get; set;}

        [Required]
        [StringLength(50)]
        public string Qualification { get; set; }

        [Required]
        [Range(1,25, ErrorMessage = "Kurang berpengalaman")]
        [DisplayName("Total Experience In Years")]
        public int TotalExperience { get; set; }
        public virtual List<Experience> Experiences { get; set; } = new List<Experience>(); // detail list Experience akan berada disini

        // menambahkan kerangka database untuk poto
        public string PhotoUrl { get; set; }

        [Required(ErrorMessage = "Please choose the profile Photo")]
        [Display(Name = "Profile Photo")]
        [NotMapped]

        public IFormFile ProfilePhoto { get; set; }
    }
}

InputAsp/Models/ErrorViewModel.cs
namespace InputAsp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InputAsp/Models/Experience.cs
 using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations.Schema;

namespace InputAsp.Models
{
    public class Experience
    {
        [Key]
        public int ExperienceId { get; set; }

        [ForeignKey("Applicant")] //sambung ke parent model
        public int ApplicantId { get; set; } //ubah tipe data menjadi int
        public virtual Applicant Applicant { get; private set; }
        public string CompanyName { get; set; }
        public string Designation { get; set; }
        [Required]
        public int YearsWorked { get; set; }
    }
}

InputAsp/Controllers/HomeController.cs
using InputAsp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InputAsp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InputAsp/Controllers/ResumeController.cs
using Microsoft.AspNetCore.Mvc;
using InputAsp.Data;
using InputAsp.Models;
using System.Linq;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace InputAsp.Controllers
{
    public class ResumeController : Controller
    {
        private readonly ResumeDbContext _context;

        private readonly IWebHostEnvironment _webHost;

        public ResumeController(ResumeDbContext context, IWebHostEnvironment webHost)
        {
            _context = context;
            _webHost = webHost;
        }

        public IActionResult Index()
        {
            List<Applicant> applicants = _context.Applicants.ToList();
            return View(applicants);
        }

        [HttpGet]
        public IActionResult Create()
        {
            Applicant applicant = new Applicant();
            applicant.Experiences.Add(new Experience() { ExperienceId = 1 });
            //applicant.Experiences.Add(new Experience() { ExperienceId = 2 });
            //applicant.Experiences.Add(new Experience() { ExperienceId = 3 });

            return View(applicant);
        }

        [HttpPost]
        public IActionResult Create(Applicant applicant)
        {
            string uniqueFileName = GetUploadFileName(applicant);
            applicant.PhotoUrl = uniqueFileName;
            _context.Add(applicant);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        private string GetUploadFileName(Applicant applicant)
        {
            string uniqueFileName = null;

            if (applicant.ProfilePhoto != null)
            {
                string uploadsFolder = Path.Combine(_webHost.WebRootPath, "Images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + applicant.ProfilePhoto.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    applicant.ProfilePhoto.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
    }
}

InputAsp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InputAsp/Views/Resume/Create.cshtml
@model InputAsp.Models.Applicant

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Applicant</h4>
<hr />

@*Penambahan untuk style design*@
<div class="col-11 mx-auto pt-0">
    <div class="card">
        <div class="card-header bg-primary text-uppercase text-white">
            <h4>Create Applicant</h4>
        </div>
        <form enctype="multipart/form-data" asp-action="Create">
            <div class="row">

                <div class="col-md-6">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Gender" class="control-label"></label>
                        <input asp-for="Gender" class="form-control" />
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Age" class="control-label"></label>
                        <input asp-for="Age" class="form-control" />
                        <span asp-validation-for="Age" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="Qualification" class="control-label"></label>
                        <input asp-for="Qualification" class="form-control" />
                        <span asp-validation-for="Qualification" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="TotalExperience" class="control-label"></label>
                        <input asp-for="TotalExperience" class="form-control" />
                        <span asp-validation-for="TotalExperience" class="text-danger"></span>
                    </div>
                </div>

                <div class="col-md-6 btn-group">
                    <div class="form-group col-8 p-0">
                        <label asp-for="ProfilePhoto" class="control-label"></label>
                        <div class="custom-file">
                            <input asp-for="ProfilePhoto" class="custom-file-input" id="customFile"
                                   onChange="document.getElementById('PreviewPhoto').src= window.URL.createObjectURL(this.files[0])" />
                            <label clas="custom-file-label" for="customFile">Choose file</label>
                        </div>
                    </div>
                    <span asp-validation-for="ProfilePhoto" class="text-danger"></span>
                </div>

                <div class="form-group d-flex justify-content-end p-5">
                    <img id="PreviewPhoto" src="~/Images/noimage.png" alt="Logo Image"
                         width="125" height="125" style="border:1px; margin-top:20px;" />
                </div>

                <div class="col-md-12">
                    <table id="ExpTable" class="table table-striped table-sm">
                        <thead>
                            <tr>
                                <th>
                                    Company Name
                                </th>
                                <th>
                                    Designation
                                </th>
                                <th>
                                    YearsWorked
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @*@foreach (var item in Model.Experiences)*@
                            @for (int i = 0; i < Model.Experiences.Count; i++)
                            {
                                <tr>
                                    <td>
                                        @Html.EditorFor(x => x.Experiences[i].CompanyName, new {htmlAttributes = new {@class = "form-control"}})
                                        @*<input asp-for="@item.CompanyName" class="form-control" />*@
                                    </td>
                                    <td>
                                        @Html.EditorFor(x => x.Experiences[i].Designation, new {htmlAttributes = new {@class = "form-control"}})
                                        @*<input asp-for="@item.Designation" class="form-control" />*@
                                    </td>
                                    <td>
                                        @Html.EditorFor(x => x.Experiences[i].YearsWorked, new {htmlAttributes = new {@class = "form-control"}})
                                        @*<input asp-for="@item.YearsWorked" class="form-control" />*@
                                    </td>
                                    <td>
                                        <button id="btnadd-@i" type="button" class="btn btn-sm btn-secondary visible" onclick="AddItem(this)">Add</button>
                                        <button id="btnremove-@i" type="button" class="btn btn-sm btn-danger invisible" onclick="RemoveItem(this)">Delete</button>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>

                <div class="col-12 btn-group d-flex justify-content-center">
                    <div class="form-group text-right p-2">
                        <a asp-action="Index" class="btn btn-secondary">Back</a>
                    </div>
                    <div class="form-group text-left p-2">
                        <input type="submit" value="Create" class="btn btn-primary" />
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script type="text/javascript">
        $('custom-file-input').on('change', function () {
            var fileName = $(this).val().split('\\').pop();
            $(this).siblings('.custom-file-label').addClass('selected').html(fileName);
        });


        function AddItem(btn) {
            var table = document.getElementById("ExpTable");
            var row = table.insertRow(-1);
            var col1 = row.insertCell(0);
            var col2 = row.insertCell(1);
            var col3 = row.insertCell(2);
            var col4 = row.insertCell(3);
            col1.innerHTML = "<input name='Experiences[" + table.rows.length + "].CompanyName' class='form-control' />";
            col2.innerHTML = "<input name='Experiences[" + table.rows.length + "].Designation' class='form-control' />";
            col3.innerHTML = "<input name='Experiences[" + table.rows.length + "].YearsWorked' class='form-control' type='number' min='0' max='50' value= '0' />";
            col4.innerHTML = "<button type='button' class='btn btn-sm btn-danger' onclick='RemoveItem(this)'>Delete</button>";
            var addButton = button.parentNode.querySelector("#btnadd");
            addButton.classList.add("invisible");
            var removeButton = button.parentNode.querySelector("#btnremove");
            removeButton.classList.remove("invisible");
        }

        function RemoveItem(btn) {
            var row = btn.parentNode.parentNode;
            var table = row.parentNode;
            table.deleteRow(row.rowIndex);
        }

    </script>
}

InputAsp/Views/Resume/Details.cshtml
@model InputAsp.Models.Applicant

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Applicant</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qualification)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qualification)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalExperience)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalExperience)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhotoUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhotoUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

InputAsp/Views/Resume/Index.cshtml
@model IEnumerable<InputAsp.Models.Applicant>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Qualification)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalExperience)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Qualification)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalExperience)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

InputAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InputAsp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InputAsp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InputAsp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Resume" asp-action="Index">Resume</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - InputAsp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>